include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Disabled: requiring docs on every public member is too strict for
    # early-stage development. Re-enable before v1.0 release.
    public_member_api_docs: false

    # Disabled: sort_pub_dependencies conflicts with grouping deps by concern.
    sort_pub_dependencies: false

    # Disabled: explicitly passing default values in theme constructors is
    # intentional — it documents design decisions and survives future default changes.
    avoid_redundant_argument_values: false
